# Site settings
title: MJD Soundboard
email: services@unc.edu
description: > # this means to ignore newlines until "baseurl:"
  Sometimes you need a little something extra to help you win at bingo.
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  sjmeijer

# Build settings
name: MJD Sounds
markdown: redcarpet
pygments: true
baseurl: /mjdSounds

