# Site settings
title: MJD Soundboard
email: services@unc.edu
description: > # this means to ignore newlines until "baseurl:"
  Sometimes you need a little something extra to help you win at bingo.
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  sjmeijer

# Build settings
name: MJD Sounds
markdown: kramdown #redcarpet
pygments: true
baseurl: /mjdSounds

  # Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-62053954-2'
  getclicky :
    site_id :